name: Enable Auto Merge
on:
  pull_request:
    branches:
      - pages

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: kenhowardpdx/auto-merge-action@v1
        if: ${{ github.actor == 'dependabot[bot]' }}